### PR TITLE
.dockerignore doesn't work if context is in a parent directory

### LINKED ISSUE #237: .dockerignore doesn't work if context is in a parent directory
E.g. if this is the directory structure:
```
skaffold/
    docker/
        Dockerfile
        .dockerignore
        ignored.txt
    tests/
        run.go
```

Then running a build from `run.go` with workspace/context = `../docker` will result in `ignored.txt` being copied into the image.

This is because the code uses `fileutils.Matches` to identify files specified by .dockerignore. And a pattern of `ignored.txt` does not match `../docker/ignored.txt`.

The solution is to make sure all file paths are relative to the context before passing them to `ApplyDockerIgnore`

### PR DESCRIPTION
**Pull request by geniass**
so dockerignore works with parent contexts

Closes #237

### CODE REVIEW

File: pkg/skaffold/docker/parse.go [hunk 1]
```diff
@@ -101,10 +101,27 @@ func GetDockerfileDependencies(workspace string, r io.Reader) ([]string, error)
 	// Look for .dockerignore.
 	ignorePath := filepath.Join(workspace, ".dockerignore")
 
-	filteredDeps, err := util.ApplyDockerIgnore(expandedDeps, ignorePath)
+	absWorkspacePath, _ := filepath.Abs(workspace)
```
Comment (dlorenc) [inline pkg/skaffold/docker/parse.go]: We should handle this error. Abs can return errors in a few cases.

Comment (geniass) [reply pkg/skaffold/docker/parse.go]: Ah missed that one. Pushed a new commit

**Comment by geniass** [comment]
@dlorenc Added the missing error check, but I noticed that the OSX test randomly failed. I don't have a Mac so I can't replicate it. Any idea what's wrong?
