### PR TITLE
Add `skaffold fix` to automatically update user configs

### LINKED ISSUE #254: Idea: skaffold fix command
As we start making changes to the config file schema, it would be nice to have a "skaffold fix" command that helps users keep up to date by applying whatever fixes we can automatically.

One rough idea for an implementation:

1. Keep all older struct versions in another package
2. If the skaffold.yaml is an older schema version or doesn't parse, try the other struct versions in reverse order
3. If it parses with one of those, tell the user to run skaffold fix to update their config
4. Every time we make a backwards-incompatible schema change, write a function to transform from one version to the next.
5. When skaffold fix is run, apply the transformation functions in order and output the new skaffold.yaml

### PR DESCRIPTION
**Pull request by nkubala**
This change adds a new command to skaffold, `fix`, which will automatically update user configs to the latest version, and output them as `<config_filename>.new` (e.g. `skaffold.yaml.new`). When an older (incompatible) config is passed to skaffold, it will tell the user to run `skaffold fix` to update their config.

Along with the addition of this command, this adds support for skaffold config versioning, which will allow us to make breaking changes to the config as needed. When these changes are made, a `Transformer` should be created with a `transform(*VersionedConfig)` method, which will convert the old version of the config into one compatible with the latest schema. These will then be applied in series to update any older config version to the latest version.

The main change to existing code is moving the main skaffold components from using structs imported from the `config` package, to using typed structs imported from `schema/<version>` (e.g `schema/v1alpha1`). This will make it more explicit when we make breaking changes to the config objects what in the code actually needs to be fixed.

This is the first code in the repo to make use of the `apiVersion` field in the config, and this is where config versioning will happen from now on.

Fixes #254

### CODE REVIEW

File: cmd/skaffold/app/cmd/fix.go [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+				return
+			}
+			if err := runFix(cfg); err != nil {
+				logrus.Errorf("fix: %s", err)
+			}
+		},
+		Args: cobra.NoArgs,
+	}
+	return cmd
+}
```
Comment (r2d4) [inline cmd/skaffold/app/cmd/fix.go]: lets add some flags to this command

string
--f, --filename, the path of the config file to fix, defaults to `skaffold.yaml`

--overwrite=true/false, whether or not to overwrite the config with the fixed one, default to false.

File: pkg/skaffold/config/config.go [hunk 2]
```diff
@@ -17,117 +17,9 @@ limitations under the License.
...
-}
-
-// Parse reads from an io.Reader and unmarshals the result into a SkaffoldConfig.
-// The default config argument provides default values for the config,
-// which can be overridden if present in the config file.
-func Parse(config []byte, defaultConfig *SkaffoldConfig) (*SkaffoldConfig, error) {
-	if err := yaml.Unmarshal(config, defaultConfig); err != nil {
-		return nil, err
-	}
+type SkaffoldConfig = v1alpha1.SkaffoldConfig
```
Comment (r2d4) [inline pkg/skaffold/config/config.go]: why do we do this instead of just using v1alpha1 everywhere?

File: pkg/skaffold/util/util.go [hunk 3]
```diff
@@ -213,3 +215,31 @@ func BoolPtr(b bool) *bool {
...
+	case filename == "-":
+		return ioutil.ReadAll(os.Stdin)
+	case strings.HasPrefix(filename, "http://") || strings.HasPrefix(filename, "https://"):
+		return Download(filename)
+	default:
+		return ioutil.ReadFile(filename)
+	}
+}
+
+func Download(url string) ([]byte, error) {
```
Comment (r2d4) [inline pkg/skaffold/util/util.go]: can we leave download private?

File: pkg/skaffold/util/util.go [hunk 4]
```diff
@@ -213,3 +215,31 @@ func BoolPtr(b bool) *bool {
...
+	resp, err := http.Get(url)
+	if err != nil {
+		return nil, err
+	}
+	defer resp.Body.Close()
+
+	return ioutil.ReadAll(resp.Body)
+}
+
+func WriteNewConfiguration(config []byte, originalFilename string) error {
```
Comment (r2d4) [inline pkg/skaffold/util/util.go]: remove this

File: pkg/skaffold/schema/transform.go [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+)
+
+type Transform func(vc *util.VersionedConfig) (*util.VersionedConfig, error)
+
+// Map of schema version to transform functions
+// If there are n schema versions, this should always contain (n-1) entries,
+// since the last schema version should not have a transform
+var transformers map[string]Transform = map[string]Transform{}
+
+func RunTransform(vc *util.VersionedConfig) (*util.VersionedConfig, error) {
```
Comment (r2d4) [inline pkg/skaffold/schema/transform.go]: can you write some tests for this?

File: pkg/skaffold/schema/util/util.go [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package util
+
+type VersionedConfig struct {
```
Comment (r2d4) [inline pkg/skaffold/schema/util/util.go]: why do we need this struct? version is already part of the config. 
can you make it an interface and then implement 

GetVersion() string for each config object?

File: cmd/skaffold/app/cmd/cmd.go [hunk 7]
```diff
@@ -75,26 +75,29 @@ func SetUpLogs(out io.Writer, level string) error {
...
 	}
 
+	if apiVersion.Version != config.LatestVersion {
+		return errors.New("Config version out of date: run `skaffold fix`")
+	}
+
 	opts.Output = out
 	opts.DevMode = dev
-	r, err := runner.NewForConfig(opts, cfg)
+	r, err := runner.NewForConfig(opts, cfg.Config.(*config.SkaffoldConfig))
```
[the remark this answers is not in the document]
Comment (nkubala) [reply cmd/skaffold/app/cmd/cmd.go]: The `VersionedConfig` is basically a holder for a `SkaffoldConfig`, which exists so we can easily pair it up with its version without having to explicitly know the type. We can unmarshal any generic config and retrieve its version. Then, if the version is older than `config.LatestVersion`, we know we need to run `skaffold fix`, otherwise we know the config is the "latest" config type, aka `config.SkaffoldConfig` (since we type aliased it there).

File: cmd/skaffold/app/cmd/cmd.go [hunk 8]
```diff
@@ -75,26 +75,29 @@ func SetUpLogs(out io.Writer, level string) error {
...
+		return errors.Wrap(err, "parsing api version")
+	}
+
+	cfg, err := config.GetConfig(buf, true, dev)
 	if err != nil {
 		return errors.Wrap(err, "parsing skaffold config")
 	}
 
+	if apiVersion.Version != config.LatestVersion {
+		return errors.New("Config version out of date: run `skaffold fix`")
```
[the remark this answers is not in the document]
Comment (nkubala) [reply cmd/skaffold/app/cmd/cmd.go]: fair enough, done

File: pkg/skaffold/config/config.go (hunk 2 above)
Comment (nkubala) [reply pkg/skaffold/config/config.go]: I wanted it to be more explicit which `SkaffoldConfig` struct is the "latest" one. The components that made up that config are versioned as well, but won't always be the same version (i.e. you could use a `v1alpha1.Artifact` and a `v2.HelmDeploy` to create a new config version). Older versions might still be used throughout the code to create the runner, watcher, etc so those can be imported directly from their version packages.

The other option is to type alias every single config component in this file, something like
```
type Artifact = v1alpha1.Artifact
type HelmDeploy = v2.HelmDeploy
...
```

but the way it is now, if you change the `v1alpha1` version of a config component it will be very explicit what in the existing code broke because of your change. I'm open to hearing arguments for doing it the other way though.

File: pkg/skaffold/util/util.go (hunk 3 above)
Comment (nkubala) [reply pkg/skaffold/util/util.go]: sure

File: pkg/skaffold/util/util.go (hunk 4 above)
Comment (nkubala) [reply pkg/skaffold/util/util.go]: This is used to write out the newly generated config

File: pkg/skaffold/schema/transform.go (hunk 5 above)
Comment (nkubala) [reply pkg/skaffold/schema/transform.go]: yeah definitely, might make sense to add them in a follow up PR once we make a config change though? since we don't have any other schemas it's a little hard to test right now.

File: pkg/skaffold/schema/util/util.go (hunk 6 above)
Comment (nkubala) [reply pkg/skaffold/schema/util/util.go]: yeah that works, updated

File: cmd/skaffold/app/cmd/cmd.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (nkubala) [reply cmd/skaffold/app/cmd/cmd.go]: Since we parse the configs into generic `SkaffoldConfig` objects, we need to type assert this to be the "latest" config before using it. `NewForConfig` uses various fields inside of the config struct (`Build`, `Deploy`, `Artifact`) which might change in the future, so I don't think it really makes sense to expose those via getter methods.

It's safe to type assert here since we already checked the API version to make sure it matches the latest version.

File: cmd/skaffold/app/cmd/fix.go (hunk 1 above)
Comment (nkubala) [reply cmd/skaffold/app/cmd/fix.go]: alright, if we don't overwrite we have two options: write to a new file (`<filename>.new`), or print to stdout but don't write a file. I personally like writing to a new file, WDYT?

File: cmd/skaffold/app/cmd/cmd.go [hunk 9]
```diff
@@ -75,26 +82,29 @@ func SetUpLogs(out io.Writer, level string) error {
...
 	}
 
+	if apiVersion.Version != config.LatestVersion {
+		return fmt.Errorf("Config version %s out of date with latest version %s: please run `skaffold fix`", apiVersion.Version, config.LatestVersion)
+	}
+
 	opts.Output = out
 	opts.DevMode = dev
-	r, err := runner.NewForConfig(opts, cfg)
+	r, err := runner.NewForConfig(opts, cfg.(*config.SkaffoldConfig))
```
Comment (r2d4) [inline cmd/skaffold/app/cmd/cmd.go]: I don't particularly like this type assertion.

File: cmd/skaffold/app/cmd/fix.go [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+			}
+			if cfg.GetVersion() == config.LatestVersion {
+				fmt.Println("config is already latest version")
+				return
+			}
+			outFile, err := runFix(cfg)
+			if err != nil {
+				logrus.Errorf("fix: %s", err)
+			}
+			fmt.Printf("New config at version %s generated and written to %s\n", config.LatestVersion, outFile)
```
Comment (r2d4) [inline cmd/skaffold/app/cmd/fix.go]: nit: fmt.Fprintf(out, "message")

File: cmd/skaffold/app/cmd/fix.go [hunk 11]
```diff
@@ -0,0 +1,79 @@
...
+			if err != nil {
+				logrus.Errorf("fix: %s", err)
+			}
+			cfg, err := config.GetConfig(contents, false, true)
+			if err != nil {
+				logrus.Error(err)
+				return
+			}
+			if cfg.GetVersion() == config.LatestVersion {
+				fmt.Println("config is already latest version")
```
Comment (r2d4) [inline cmd/skaffold/app/cmd/fix.go]: nit: fmt.Fprintf(out, "message")

File: pkg/skaffold/util/util.go [hunk 12]
```diff
@@ -213,3 +215,36 @@ func BoolPtr(b bool) *bool {
...
+	resp, err := http.Get(url)
+	if err != nil {
+		return nil, err
+	}
+	defer resp.Body.Close()
+
+	return ioutil.ReadAll(resp.Body)
+}
+
+func WriteNewConfiguration(config []byte, originalFilename string, overwrite bool) (string, error) {
```
Comment (r2d4) [inline pkg/skaffold/util/util.go]: can we make this print to stdout instead? Let this function take in an io.Writer from the cmd

File: cmd/skaffold/app/cmd/cmd.go [hunk 13]
```diff
@@ -75,26 +82,29 @@ func SetUpLogs(out io.Writer, level string) error {
...
-	buf, err := readConfiguration(filename)
+	buf, err := util.ReadConfiguration(filename)
 	if err != nil {
 		return errors.Wrap(err, "read skaffold config")
 	}
 
-	defaultConfig := defaultConfigForMode[dev]
-	cfg, err := config.Parse(buf, defaultConfig)
+	apiVersion := &config.ApiVersion{}
+	if err := yaml.Unmarshal(buf, apiVersion); err != nil {
```
Comment (r2d4) [inline cmd/skaffold/app/cmd/cmd.go]: I'm a little worried about fix and dev/run going through the same codepath. Can we hardcode the latest version here?

Would it be possible to keep this machinery the same and only use the conversion code in fix?

File: pkg/skaffold/schema/v1alpha1/config.go [hunk 14]
```diff
@@ -0,0 +1,146 @@
...
+var DefaultRunSkaffoldConfig = &SkaffoldConfig{
+	Build: BuildConfig{
+		TagPolicy: constants.DefaultRunTagStrategy,
+	},
+}
+
+// Parse reads from an io.Reader and unmarshals the result into a SkaffoldConfig.
+// The default config argument provides default values for the config,
+// which can be overridden if present in the config file.
+func (config *SkaffoldConfig) Parse(contents []byte, useDefault bool, mode bool) error {
```
[the remark this answers is not in the document]
Comment (nkubala) [reply pkg/skaffold/schema/v1alpha1/config.go]: yeah I went back and forth on this one, but ended up moving it there because each implementation of `Parse` uses different default values which are bound to the versioned config. I could hear arguments to move it out but to do that we'd need to have some other logic somewhere else that tells us which default to use, and I'm not sure what that would look like

File: pkg/skaffold/schema/util/util.go [hunk 15]
```diff
@@ -0,0 +1,26 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package util
+
+type VersionedConfig interface {
+	GetVersion() string
+	Parse([]byte, bool, bool) error
```
[the remark this answers is not in the document]
Comment (nkubala) [reply pkg/skaffold/schema/util/util.go]: the second bool here is ignored when the first one is passed as `false`: `useDefault` tells us if we should use default values for the config, and then `dev` tells us which default to use, so if we're not using a default value it doesn't matter which is passed for the second bool

File: pkg/skaffold/config/util.go [hunk 16]
```diff
@@ -0,0 +1,51 @@
...
+	"errors"
+
+	"github.com/GoogleCloudPlatform/skaffold/pkg/skaffold/schema/util"
+	"github.com/GoogleCloudPlatform/skaffold/pkg/skaffold/schema/v1alpha1"
+)
+
+// Ordered list of all schema versions
+var Versions = []string{v1alpha1.Version}
+
+var schemaVersions map[string]func([]byte, bool, bool) (util.VersionedConfig, error) = map[string]func([]byte, bool, bool) (util.VersionedConfig, error){
```
[the remark this answers is not in the document]
Comment (nkubala) [reply pkg/skaffold/config/util.go]: this is a map of versions, to functions which create a new versioned config and call its `Parse()` implementation with the contents of the user's config.

File: cmd/skaffold/app/cmd/cmd.go (hunk 9 above)
Comment (nkubala) [reply cmd/skaffold/app/cmd/cmd.go]: I'm not the biggest fan of it either, but the alternative is exposing all fields in a config through getter methods and then refactoring all skaffold components to call those methods to retrieve the fields they need. this also binds us to those fields and makes it a lot harder to make major config changes down the road, since we'd need to go change all the callers of those methods. definitely open to suggestions here but I still think this is the best way to handle this

File: cmd/skaffold/app/cmd/fix.go (hunk 10 above)
Comment (nkubala) [reply cmd/skaffold/app/cmd/fix.go]: ahh yeah good call

File: cmd/skaffold/app/cmd/fix.go (hunk 11 above)
Comment (nkubala) [reply cmd/skaffold/app/cmd/fix.go]: done

File: pkg/skaffold/util/util.go (hunk 12 above)
Comment (nkubala) [reply pkg/skaffold/util/util.go]: fixed. moved this logic into the cmd itself, and stuck with using `ioutil.WriteFile` if we're overwriting since you can't overwrite a file using `bufio.NewWriter` without explicitly deleting the file first, which I definitely don't want to do.

File: cmd/skaffold/app/cmd/cmd.go (hunk 13 above)
Comment (nkubala) [reply cmd/skaffold/app/cmd/cmd.go]: The only codepath they really share is the config parsing, fix just tries to parse the config first to see if it's already the latest version. `config.Parse()` doesn't really do anything fancy except iterate through config versions and attempt to parse into each one, the transforms all happen separately and aren't touched by dev/run.

I'm not huge on hardcoding the latest version here, it's already basically hardcoded through the type definition in config/config.go.

File: pkg/skaffold/schema/v1alpha2/config.go [hunk 17]
```diff
@@ -0,0 +1,102 @@
...
+	KubectlDeploy *KubectlDeploy       `yaml:"kubectl,omitempty"`
+}
+
+// KubectlDeploy contains the configuration needed for deploying with `kubectl apply`
+type KubectlDeploy struct {
+	Manifests []string `yaml:"manifests"`
+}
+
+type BuildConfig struct {
+	Artifacts          []*v1alpha1.Artifact `yaml:"artifacts"`
```
Comment (r2d4) [inline pkg/skaffold/schema/v1alpha2/config.go]: I think i might have suggested reusing v1alpha1, but we shouldn't reference v1alpha1 anywhere from alpha2 or in the code

Comment (r2d4) [reply pkg/skaffold/schema/v1alpha2/config.go]: I would just duplicate them here.

File: skaffold.yaml.old [hunk 18]
```diff
@@ -0,0 +1,16 @@
+apiVersion: skaffold/v1alpha1
```
Comment (r2d4) [inline skaffold.yaml.old]: remove this file

File: examples/old-config/skaffold.yaml [hunk 19]
```diff
@@ -0,0 +1,12 @@
+apiVersion: skaffold/v1alpha2
```
[the remark this answers is not in the document]
Comment (nkubala) [reply examples/old-config/skaffold.yaml]: yeah fair enough, it's basically a duplicate of the getting started example anyway

File: pkg/skaffold/schema/v1alpha2/config.go (hunk 17 above)
Comment (nkubala) [reply pkg/skaffold/schema/v1alpha2/config.go]: talked about this out of band, going to go ahead and duplicate config components here for now. if we want to go and type alias them in `config.go` later on that's always an option.

**Comment by dgageot** [comment]
@nkubala Sorry, the PR needs a rebase
